services:
  db:
    image: mysql:8.0
    container_name: db_educart
    restart: always
    environment:
      MYSQL_DATABASE: 'db_educart_quiz'
      MYSQL_USER: 'user_educart'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  fakemail:
    container_name: fakemail
    image: gessnerfl/fake-smtp-server:latest
    restart: always
    ports:
      - "5080:8080"
      - "8025:8025"
  web:
    build: . 
    volumes:
      - .:/app 
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: "python manage.py runserver 0.0.0.0:8000"
volumes:
  my-db: 
    driver: local
