version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: db_educart
    restart: always
    environment:
      MYSQL_DATABASE: 'db_educart_quiz'
      MYSQL_USER: 'user_educart'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: 
    driver: local