"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os

from pathlib import Path

from import_export.formats.base_formats import CSV, XLSX


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SITE_URL = os.environ.get("SITE_URL", "http://localhost:8000")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g0_%f&v35*+w4srab9jes!9m)877ybk+0ff!s&p!at(%!3pwhp' # noqa

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # Add-ons
    'crispy_forms',
    'crispy_bootstrap4',
    'import_export',
    'mercadopago',
    'request_token',
    # Apps
    'core',
    'planos',
    'quiz',
    'usuarios',
    'pagamentos',
    'notificacoes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Add-ons
    'request_token.middleware.RequestTokenMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_educart_quiz',
        'USER': 'user_educart',
        'PASSWORD': 'password',
        'HOST':  '127.0.0.1',
        'PORT':  '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', # noqa
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', # noqa
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', # noqa
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', # noqa
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

MEDIA_URL = 'mediafiles/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/mediafiles')

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static/'
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# JAZZMIN_SETTINGS = {
#     # title of the window (Will default to current_admin_site.site_title if absent or None) # noqa
#     "site_title": "Library Admin",
#
#     # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None) # noqa
#     "site_header": "Library",
#
#     # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None) # noqa
#     "site_brand": "Library",
#
#     # Logo to use for your site, must be present in static files, used for brand on top left # noqa
#     "site_logo": "imgs/logo.png",
# }

# Login

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_USE_TLS = False
EMAIL_PORT = 8025
EMAIL_HOST_USER = 'atendimento@pamas.com.br'
EMAIL_HOST_PASSWORD = ''

# JWT Request Token
REQUEST_TOKEN_EXPIRY = '1d'
REQUEST_TOKEN_DEFAULT_MAX_USES = 10
FOUR03_TEMPLATE = os.path.join(BASE_DIR, '...', '403.html')

# Logging
LOGGING = {
    'version': 1,  # the dictConfig format version
    'disable_existing_loggers': False,  # retain the default loggers
    'formatters': {
        'simple': {
            'format': '[{asctime}] "{funcName}" {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        }
    },
    'loggers': {
        '': {
            'level': 'INFO',
            'handlers': ['console'],
        }
    }    
}

MERCADOPAGO_CLIENT_ID = os.environ.get('MERCADOPAGO_CLIENT_ID', '4634839706246803')
MERCADOPAGO_CLIENT_SECRET = os.environ.get('MERCADOPAGO_CLIENT_SECRET', 'tRgjoQzo0iCZnKH2xMFDiq37K2vDgG6d')
MERCADOPAGO_PUBLIC_KEY = os.environ.get('MERCADOPAGO_CLIENT_SECRET', 'APP_USR-3aa02b1a-b3f4-480b-8358-08f3404d2a5e')
MERCADOPAGO_ACCESS_TOKEN = os.environ.get('MERCADOPAGO_CLIENT_SECRET', 'APP_USR-4634839706246803-052314-df109ee7ee48312e774f0fe89adce662-2360331')

DATE_FORMAT_DEFAULT = '%d/%m/%y'
DATETIME_FORMAT_DEFAULT = '%d/%m/%y %H:%m:%s'
TIMEOUT_FORMULARIO = 15 # Minutos

IMPORT_FORMATS = [CSV, XLSX]

# try:
#     from core.local_settings import *
# except ImportError:
#     print("sem o arquivo local_settings")