
name: Collectstatic for Django Static Files

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run Collectstatic
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          python manage.py collectstatic --noinput